name: Push to Docker Hub then to GHCR
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the cent7-nimble-publish-to-gcr Docker image
        run: |
          docker build . --tag ghcr.io/drunkod/cent7-nimble-publish-to-gcr:latest
          docker run ghcr.io/drunkod/cent7-nimble-publish-to-gcr:latest
          docker push ghcr.io/drunkod/cent7-nimble-publish-to-gcr:latest
